### ISSUE TITLE
use motor with api-hour

### ISSUE THREAD

**Issue by njordr** [Eyepea/API-Hour#4]
Hi.

Apologize if I open an issue but I cannot post on google groups (don't know why)

I would like to use motor with api-hour, but I can't understand how to implement it.

I'm stucked here:
@asyncio.coroutine
def start(self):
    yield from super().start()
    LOG.info('Starting engines...')
    '''
    # Add your custom engines here, example with PostgreSQL:
    self.engines['pg'] = self.loop.create_task(aiopg.create_pool(host=self.config['engines']['pg']['host'],
                                                                 port=int(self.config['engines']['pg']['port']),
                                                                 sslmode='disable',
                                                                 dbname=self.config['engines']['pg']['dbname'],
                                                                 user=self.config['engines']['pg']['user'],
                                                                 password=self.config['engines']['pg']['password'],
                                                                 cursor_factory=psycopg2.extras.RealDictCursor,
                                                                 minsize=int(self.config['engines']['pg']['minsize']),
                                                                 maxsize=int(self.config['engines']['pg']['maxsize']),
                                                                 loop=self.loop))
    '''
    self.engines['mongo'] = motor_asyncio.AsyncIOMotorClient()
    # yield from asyncio.wait([self.engines['pg']], return_when=asyncio.ALL_COMPLETED)
    yield from asyncio.wait([self.engines['mongo']], return_when=asyncio.ALL_COMPLETED)

I can't understand how to initialize motor.

Many thanks,
giovanni

**Comment by iCart** [comment]
Hi njordr,

You couldn't post on the google groups because we needed to validate your membership first (which i did, so you should be able to, now).

To solve your issue: it seems that `motor_asyncio.AsyncIOMotorClient()` does not return a coroutine, so you can just comment out (or remove) the line that says `yield from asyncio.wait([self.engines['mongo']], return_when=asyncio.ALL_COMPLETED)` and you should be good.

In your endpoint you can do `db = request.app['ah_container].engines['mongo']` to retrieve the motor instance.

Hope this helps!

**Comment by njordr** [comment]
Great, thank you
